version: '2'
services:
  zebra:
    image: contrail-quagga-zebra:4.0.0.0-20
    env_file: ../common.env
    network_mode: host
    privileged: true
    volumes:
     - /etc/quagga
  ospf:
    image: contrail-quagga-ospf:4.0.0.0-20
    env_file: ../common.env
    network_mode: "service:zebra"
    privileged: true
    volumes_from:
     - zebra
