version: '2'
services:
  network:
    image: docker.io/kubernetes/pause
    network_mode: "host"
  api:
    image: 10.87.64.33:5043/contrail-analytics-api:4.0.0.0-20
    env_file: ../common.env
    network_mode: "service:network"
    depends_on:
      - network
